### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by anfeloga** [cedaro/woocommerce-coupon-links#13]
Hi

![coupon](https://cloud.githubusercontent.com/assets/3213358/14150683/d1d88fdc-f66f-11e5-9fd1-7e81b020c605.png)

As You can see the coupon is not being applied for me. I'm using MyMail to send an automated email with a coupon code to those who suscribe to my site via a popup and in the email I added a button with a coupon called firstone in order to get 10% discount but after make a test email and try it, the coupon is not being applied.

I have the last version of MyMail, WP, WooCommerce and WooCommerce Coupon Links.

Any idea? Thanks in advance!

**Comment by hjoelr** [comment]
@anfeloga It could be that your session/cookies need cleared for it to properly work. An easy way to test that is to open a Google Chrome incognito window, go to your store and add the product to the cart and then use the coupon link in there to see if it worked.

Here are a couple other things to check for:

- Is the extension activated on the site you're trying to use it on?
- Does the coupon code work for the product that you have in the cart?
- Was the product in the cart before you tried to apply the coupon?
- Were there any notifications on the front end when you tried to use the coupon that would cue you in on some problem that may have happened?

**Comment by anfeloga** [comment]
@hjoelr, many thanks. Actually I don't know why but for some reason the plugin was deactivated. I just activated again and now everything is working awesome.

Thanks a lot!

**Comment by hjoelr** [comment]
@anfeloga Great! Glad it was an easy fix.
