### ISSUE TITLE
session/cookie problem

### ISSUE THREAD

**Issue by wouters** [cedaro/woocommerce-coupon-links#14]
He there,

I'm trying to get the plugin working with the latest versions of WooCommerce and Wordpress. But the coupon is only applied the second time i click the link. i tried disabling all plugins that might interfere but i can't find a reason why it is behaving this way. Anyone else experiencing this behaviour?

**Comment by bradyvercher** [comment]
Hi @wouters. I haven't come across that issue, but let me know if you find anything out. I've recently started working on some tests, so if you can figure out what's going on, we can look into adding a test for it.

**Comment by wouters** [comment]
He thanks for letting me know. I think i found it. Turns out that there's a line in the theme that is hiding the coupon field when the order total is 0. But since the coupon is added before the product this is also disabling the coupon. So what i did is add a simple extra check to the filter to see if there's no variable in the url. If anyone else is interested in this, here's the code:

```
add_filter( 'woocommerce_coupons_enabled', 'hide_coupon_field' );
function hide_coupon_field( $enabled ) {
	global $woocommerce;
	$query_var = apply_filters( 'woocommerce_coupon_links_query_var', 'coupon_code' );

	if (0 == $woocommerce->cart->total && empty( $_GET[ $query_var ] ) && count($woocommerce->cart->applied_coupons) == 0) { $enabled = false; }
	return $enabled;
	}
```
