### ISSUE TITLE
Conflicts with latest WC cart ajax "remove" coupon link.

### ISSUE THREAD

**Issue by adaptifyDesigns** [cedaro/woocommerce-coupon-links#15]
Hi. Firstly, thank you so much for your extremely helpful plugin! I really appreciate it.

I am finally upgrading to WooCommerce 2.6.x which comes with some nice ajax enhancements on the cart page for adding/removing products, updating quantities, AND adding/removing coupons. 

Here is the scenario:

Customer clicks on a custom add coupon link, which uses your plugin's coupon URL parameter to reload the page and apply the given coupon to the cart. 

So now the URL looks something like this: `/cart/?coupon_code=highfive`

But now the customer realizes that they didn't want that specific coupon applied, so they click the "[remove]" link next to the coupon line item in the cart totals table... WooCommerce's new ajax kicks in and tries to remove the coupon without reloading the page. 

The problem is that woocommerce-coupon-links attempts to parse the URL parameter, which is still present, and so the coupon is re-applied and the "[remove]" link becomes useless :-(

I took a look at the WooCommerce [cart.js](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/cart.js), but it looks like each ajaxified action has it's own specific class and ajax handle. In other words, there isn't a universal helper class that I can simply apply to my custom add-coupon link to make it also use the WC ajax, so I'm unsure of how to resolve this issue.

Perhaps it is necessary to enhance this plugin to accommodate the new WC cart ajax features.

Please let me know your thoughts on the matter.

Cheers!

**Comment by bradyvercher** [comment]
Hi @adaptifyDesigns, thanks for the report! This is probably something that needs to be handled in the plugin itself, but I'm not seeing any hooks in WooCommerce that would make it easy.

A redirect to remove the coupon query string argument would likely create unintentional side effects.

My current thinking is to prevent the coupon from being applied during AJAX requests and print a snippet of JavaScript to remove the coupon code query string argument using the browser's History API.

**Comment by adaptifyDesigns** [comment]
Using the JS History API is a clever idea. 

Because my use case is confined to the cart page itself, for now I'm just going to replace my coupon link with a custom coupon form submit button with hidden coupon text field. Unfortunately I don't know how to leverage the WC cart ajax, so the page still has to reload, but it effectively applies the coupon.

I wish I had time to help develop a solution to the issue, but I'm slammed at the moment.

Let me know if you end up making any updates.

Cheers!

**Comment by bradyvercher** [comment]
Hi @adaptifyDesigns, I went ahead and implemented the two updates I mentioned earlier, so I think this should be good to go. Let me know if it doesn't resolve the issue you described or if you run into any other problems. Thanks again for the report.
