### ISSUE TITLE
Not applying coupons correctly if outside cart or checkout

### ISSUE THREAD

**Issue by jdiaz1302** [cedaro/woocommerce-coupon-links#16]
Hey there, I've created a coupon and I want that when someone clicks the link they will be directed to a specific page where they will see product information, but when I click a link there selecting one of the options I get a message saying that "Sorry, this coupon is only valid for subscription products." or any other page, I have to include the specific product with coupon and it works, also if you add it in the coupon field the the coupon is applied without any trouble.

As I understand it should also work if you create links outside the cart or checkout, right? 

Thanks in advance!

**Comment by silicondales** [comment]
I got this issue just now. Coupon not applying when deferred. It worked before recent update... I'm going to have a look at what's changed here.

**Comment by silicondales** [comment]
The update was to woocommerce, not this plugin.

**Comment by bradyvercher** [comment]
It sounds like there was some sort of exclusion that prevented the coupon from being applied. I believe the coupon field is only visible when a product is added to the cart, which is probably why the coupon would work in that case, but not when applied through a URL.
