### ISSUE TITLE
"coupon-code", not "coupon_code"

### ISSUE THREAD

**Issue by aleks1217** [cedaro/woocommerce-coupon-links#18]
I've been struggling to get the /cart/?coupon_code=XXX trick to work, and just discovered it needs to be a hyphen, not underscore. Correct usage is /cart/?**coupon-code**=XXX

**Comment by bradyvercher** [comment]
Hi @aleks1217, The correct query var is actually `coupon_code` with an underscore as [seen in the code here](https://github.com/cedaro/woocommerce-coupon-links/blob/ebe9d83d3cb32c0402be21e83ecd15976f026a7d/woocommerce-coupon-links.php#L52). I'm not sure why the hyphen worked for you unless you're using a different plugin or something is filtering that default value.
