### ISSUE TITLE
Sorry, this coupon is not applicable to selected products.

### ISSUE THREAD

**Issue by metlock** [cedaro/woocommerce-coupon-links#20]
Nice plugin, problem I cant get past is the error: Sorry, this coupon is not applicable to selected products.

applicable Products have been included in the coupon and I'm using the right ID for the product. Have tried adding first Variant and all variants still wont detect correctly. 
It works fine with no products set as a global discount code
Any ideas?

**Comment by bradyvercher** [comment]
Hi @metlock, I don't have any ideas at the moment, but it seems like something may have changed in a recent WooCommerce release, so this is something I'll have to dig into when I get a little time.

**Comment by bradyvercher** [comment]
I spent a little time today tracking down an unrelated issue that was causing some problems with this plugin, so I looked into what could cause the error you're seeing. It looks like that particular error is returned in three cases:

1. When the coupon is limited to specified products ([`WC_Discounts::validate_coupon_product_ids()`](https://github.com/woocommerce/woocommerce/blob/67144be6283e293a1652ee4139bad57497b2a446/includes/class-wc-discounts.php#L663))
2. When the coupon is limited to products in specified categories ([`WC_Discount::validate_product_coupon_categories()`](https://github.com/woocommerce/woocommerce/blob/67144be6283e293a1652ee4139bad57497b2a446/includes/class-wc-discounts.php#L701))
3. When the coupon excludes specific products ([`WC_Discount::validate_coupon_excluded_items()`](https://github.com/woocommerce/woocommerce/blob/67144be6283e293a1652ee4139bad57497b2a446/includes/class-wc-discounts.php#L755)

You might make sure the product/variation that you're using doesn't match any of those criteria.
