### ISSUE TITLE
Coupon is not working when we set up discount type as Recurring Product % Discount

### ISSUE THREAD

**Issue by sarun007** [cedaro/woocommerce-coupon-links#21]
I set up a coupon in woocommerece. On the coupon settings i selected Discount type as **_Recurring Product % Discount_**.Then i applied coupon like this **https://audiotheme.com/?coupon_code=highfive** at that time coupon is not applied.

I changed the coupon discount type as **_percentage discount_** then the coupon url like this  **https://audiotheme.com/?coupon_code=highfive**  is working.Then the coupon is applied on the cart.

The _**Recurring Product % Discount**_ type coupon is only working like this URL **https://audiotheme.com/view/promenade/?add-to-cart=2804&coupon_code=highfive**.

How to solve this problem?

**Comment by bradyvercher** [comment]
Some coupons can't be applied if the cart doesn't contain a product that matches conditions required by the coupon. In this case, it sounds like you're trying to apply a recurring percentage discount to a cart without a subscription, which is probably throwing an error.

The validation logic for WooCommerce [can be seen here](https://github.com/woocommerce/woocommerce/blob/bbc472d80d393c0b3db1578f3e53420f2e4f57e8/includes/class-wc-discounts.php#L863-L920). The Subscriptions extension hooks in to that `woocommerce_coupon_is_valid` filter, so you'd need to take a look at `WC_Subscriptions_Coupon::validate_subscription_coupon_for_cart()` to see what rules it implements.
