### ISSUE TITLE
The coupon with url is not working for me 

### ISSUE THREAD

**Issue by sarun007** [cedaro/woocommerce-coupon-links#22]
Before updating woocommerce and woocommerce-coupon-link my couopn url is working for me.My url is like **https://audiotheme.com/?coupon_code=highfive** .And after the updation of woocommerce and coupon link plugin my coupon with url is not working this is my url https://audiotheme.com/?coupon_code=highfive. And also we didn't have cart page we have direct checkout on my site.

**Comment by bradyvercher** [comment]
Hi @sarun007, were you ever able to figure out what this issue might be? There isn't really enough information here for me to troubleshoot or make any recommendations.
