### ISSUE TITLE
Updated for WooCommerce 3.4.4?

### ISSUE THREAD

**Issue by mj445** [cedaro/woocommerce-coupon-links#24]
Hello! I am very excited about this plugin, but I can't seem to get it to work. Has it been updated for compatibility with WooCommerce 3.4.4? Thank you!

**Comment by bradyvercher** [comment]
Hi @mj445, it should work fine with WooCommerce 3.4.4. Can you provide more information about what isn't working for you?

**Comment by mj445** [comment]
Hello! Thank you for your response! My apologies - the plugin works great! I was accidentally putting "coupon-code" instead of "coupon_code" in the URL. That is the type of URL used with WooCommerce Smart Coupons, which I am replacing with your awesome plugin! So, I just changed all "coupon_code" text in your plugin file to "coupon-code" and voila! I have the perfect replacement with a nice, clean plugin. Thank you so much! :)
