### ISSUE TITLE
Coupon gets automatically removed during checkout on live machine

### ISSUE THREAD

**Issue by maisnamraju** [cedaro/woocommerce-coupon-links#5]
For some reason the coupon gets applied and then gets removed automatically after a second or so in the live setup. I have checked for conflicts with other plugins and there doesn't seem to be one. Any ideas on why this could be happening.

Nice plugin btw.

**Comment by bradyvercher** [comment]
Hi @maisnamraju, do you have a link where I can see that behavior? We're running it at the demo URL in the README and I haven't noticed any issues.

**Comment by maisnamraju** [comment]
Hey @bradyvercher  sorry for the late reply but i don't have a link to it any more. I had to stop using the plugin, but I am guessing it could have been my server settings.
