### ISSUE TITLE
if cart is empty, coupon seems to be correctly applied, then it's not :(

### ISSUE THREAD

**Issue by alemarengo** [cedaro/woocommerce-coupon-links#8]
Hi!
As in the subject, if I go to http://www.website.net/carrello/?coupon_code=custom-coupon-code, cart notice correctly shows up. After that, when I put a product on the cart, coupon is not visible.
In my config, it's visible thanks to the Smart Coupon installed plugin.
In addition, related to coupons, in my config I also installed WooCommerce Extended Coupon Features.
Can you help me discover how to fix this? I mean, how can I leave the coupon called via url still there until a product will be put in the cart?
Thanks in advance!

**Comment by jameslporter** [comment]
I thought the same thing however it applies correctly if landing on a product page or a product category page. The shop home page does not apply with when there is no product context.
